### ISSUE TITLE
composer dependency conflict with Laravel v9

### ISSUE THREAD

**Issue by benlongstaff** [php-pdfbox/php-pdfbox#6]
I am trying to install php-pdfbox into a laravel project, when trying to install with 
`sail composer require php-pdfbox/php-pdfbox:v1.0.4`

I get the error
>  Problem 1
>
>     - Root composer.json requires php-pdfbox/php-pdfbox v1.0.4 -> satisfiable by php-pdfbox/php-pdfbox[v1.0.4].
>     - php-pdfbox/php-pdfbox v1.0.4 requires psr/log ^1.0 -> found psr/log[1.0.0, ..., 1.1.4] but the package is fixed to 3.0.0 (lock file version) by

 a partial update and that version does not match. Make sure you list it as an argument for the update command.

running with -W 
`./vendor/bin/sail composer require php-pdfbox/php-pdfbox:v1.0.4 -W`
 gives

>  Problem 1
>
>    - Root composer.json requires php-pdfbox/php-pdfbox v1.0.4 -> satisfiable by php-pdfbox/php-pdfbox[v1.0.4].
>    - php-pdfbox/php-pdfbox v1.0.4 requires symfony/process ^5.0 -> found symfony/process[v5.0.0-BETA1, ..., 5.4.x-dev] but these were not loaded, likely because it conflicts with another require.`

when specifying 
` "symfony/process": "^5.0"`
as a requirement to see where the conflict is gives 

>   Problem 1
>    - laravel/framework[v9.19.0, ..., 9.x-dev] require symfony/process ^6.0 -> found symfony/process[v6.0.0-BETA1, ..., 6.3.x-dev] but it conflicts with your root composer.json require (^5.0).
>    - Root composer.json requires laravel/framework ^9.19 -> satisfiable by laravel/framework[v9.19.0, ..., 9.x-dev].

**Comment by redcuillin** [comment]
The current version of still has some problems with PHP8+. I was trying to get it to support both PHP7.4 and PHP8.1+, but unfortunately the dependencies break, so I'm working on releasing a v2.0 release which drops PHP7.4 support.

**Comment by redcuillin** [comment]
You should be able to manually install the php8development branch if you want to see if that fixes the problem for you.

**Comment by redcuillin** [comment]
Try installing the development branch by editing your composer.json to read

`"php-pdfbox/php-pdfbox": "dev-php8development",`

**Comment by redcuillin** [comment]
Completed
